version: "3"

services:
  db:
    container_name: mysql-db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: 'proyecto2'
      MYSQL_PASSWORD: '1234'
      
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./db_data:/var/lib/mysql
  
volumes:
  db_data: